version: "3"
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=heh
      - DATABASE_USERNAME=postgres
      - DATABASE_PORT=5432
      - SECRET_KEY=fd1d44c2ea01d65129d71f8fe0636779d945bcec90fc51bdfb1a4ef3a1a70d5b
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=heh
      - POSTGRES_USER=postgres